import type { ServiceSchema } from './types.js';

export const SERVICE_SCHEMAS: ServiceSchema[] = [
  {
    service: 'discord',
    label: 'Discord',
    description: 'Send notifications via Discord webhooks',
    schemes: ['discord'],
    category: 'chat',
    iconHint: 'discord',
    fields: [
      {
        key: 'webhook_id',
        label: 'Webhook ID',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: '1234567890',
        helpText: 'In your Discord server: Server Settings → Integrations → Webhooks → select or create a webhook → Copy Webhook URL. The webhook ID is the number after /webhooks/ in the URL.',
        validation: { pattern: '^\\d+$' },
      },
      {
        key: 'webhook_token',
        label: 'Webhook Token',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'abcdefghijklmnopqrst...',
        helpText: 'The token comes after the webhook ID in the webhook URL (the last path segment).',
      },
    ],
  },
  {
    service: 'slack',
    label: 'Slack',
    description: 'Send notifications via Slack incoming webhooks',
    schemes: ['slack'],
    category: 'chat',
    iconHint: 'slack',
    fields: [
      {
        key: 'token_a',
        label: 'Token A',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'T00000000',
        helpText: 'Create an incoming webhook at api.slack.com/apps → your app → Incoming Webhooks. The webhook URL looks like hooks.slack.com/services/TOKEN_A/TOKEN_B/TOKEN_C.',
      },
      {
        key: 'token_b',
        label: 'Token B',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'B00000000',
        helpText: 'The second path segment in the Slack webhook URL (after /services/).',
      },
      {
        key: 'token_c',
        label: 'Token C',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'XXXXXXXXXXXXXXXXXXXXXXXX',
        helpText: 'The third path segment in the Slack webhook URL. Treat this as a secret.',
      },
      {
        key: 'channel',
        label: 'Channel',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: '#general',
        helpText: 'Override the default channel (e.g. #alerts). Leave blank to use the channel configured in the webhook settings.',
      },
    ],
  },
  {
    service: 'telegram',
    label: 'Telegram',
    description: 'Send notifications via Telegram bot messages',
    schemes: ['tgram'],
    category: 'chat',
    iconHint: 'telegram',
    fields: [
      {
        key: 'bot_token',
        label: 'Bot Token',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: '123456789:AABBccDDeeff...',
        helpText: 'Create a bot via @BotFather on Telegram (/newbot). The bot token is provided after creation.',
      },
      {
        key: 'chat_id',
        label: 'Chat ID',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: '-1001234567890',
        helpText: 'The chat ID to send messages to. Forward a message to @userinfobot to get your chat ID, or use the Telegram API getUpdates method.',
      },
    ],
  },
  {
    service: 'ntfy',
    label: 'ntfy',
    description: 'Send notifications via ntfy.sh or a self-hosted ntfy server',
    schemes: ['ntfy'],
    category: 'self-hosted',
    iconHint: 'bell',
    fields: [
      {
        key: 'topic',
        label: 'Topic',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'my-alerts',
        helpText: 'The ntfy topic to publish to. Topics are auto-created on first use. Choose a hard-to-guess name since ntfy.sh topics are public.',
      },
      {
        key: 'host',
        label: 'Host',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'ntfy.sh',
        defaultValue: 'ntfy.sh',
        helpText: 'Your self-hosted ntfy server hostname. Leave blank or set to ntfy.sh to use the public server.',
      },
    ],
  },
  {
    service: 'gotify',
    label: 'Gotify',
    description: 'Send notifications via a self-hosted Gotify server',
    schemes: ['gotify'],
    category: 'self-hosted',
    iconHint: 'server',
    fields: [
      {
        key: 'host',
        label: 'Server Host',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'gotify.example.com',
        helpText: 'The hostname of your Gotify server (without https://). Set up your own at gotify.net.',
      },
      {
        key: 'token',
        label: 'App Token',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'Axxxxxxxxxxxxxx',
        helpText: 'Create an application in your Gotify dashboard and copy its token.',
      },
    ],
  },
  {
    service: 'email',
    label: 'Email (via Gateway)',
    description: 'Send email notifications via MailChannels or Resend HTTP gateway',
    schemes: ['mailto'],
    category: 'email',
    iconHint: 'mail',
    fields: [
      {
        key: 'to',
        label: 'Recipient Email',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'recipient@example.com',
        helpText: 'The email address to send notifications to.',
        validation: { pattern: '^[^@]+@[^@]+\\.[^@]+$' },
      },
      {
        key: 'gateway',
        label: 'Gateway',
        type: 'select',
        required: true,
        sensitive: false,
        helpText: 'Raw SMTP is not supported in Web API environments. Choose a gateway: MailChannels is free on Cloudflare Workers; Resend has a free tier.',
        options: [
          { label: 'MailChannels (free on Cloudflare Workers)', value: 'mailchannels' },
          { label: 'Resend (free tier)', value: 'resend' },
        ],
      },
      {
        key: 'user',
        label: 'Username / Sender',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'noreply',
        helpText: 'The local part of the sender email address (before @host). Used to construct the From address.',
      },
      {
        key: 'host',
        label: 'Domain',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'example.com',
        helpText: 'The domain part of the sender address.',
      },
      {
        key: 'api_key',
        label: 'API Key (Resend only)',
        type: 'text',
        required: false,
        sensitive: true,
        placeholder: 're_xxxxxxxxxx',
        helpText: 'Your Resend API key — found at resend.com → API Keys. Only required when using the Resend gateway.',
      },
      {
        key: 'from',
        label: 'From Address (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'alerts@example.com',
        helpText: 'Override the sender email address.',
        validation: { pattern: '^[^@]+@[^@]+\\.[^@]+$' },
      },
      {
        key: 'cc',
        label: 'CC (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'cc@example.com',
        helpText: 'Carbon copy recipient.',
      },
      {
        key: 'bcc',
        label: 'BCC (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'bcc@example.com',
        helpText: 'Blind carbon copy recipient.',
      },
    ],
  },
  {
    service: 'msteams',
    label: 'Microsoft Teams',
    description: 'Send notifications via Microsoft Teams incoming webhooks',
    schemes: ['msteams', 'teams'],
    category: 'chat',
    iconHint: 'teams',
    fields: [
      {
        key: 'group_id',
        label: 'Group / Workspace GUID',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        helpText: 'From your Teams webhook URL: the GUID before the @ in the webhookb2 path segment. Go to Teams channel → Connectors → Incoming Webhook → configure to get the URL.',
      },
      {
        key: 'tenant_id',
        label: 'Tenant GUID (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy',
        helpText: 'The GUID after the @ in the webhookb2 path segment. Leave blank if your webhook URL does not have an @ in that segment.',
      },
      {
        key: 'channel_id',
        label: 'Channel ID',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'zzzzzzzz',
        helpText: 'The path segment after /IncomingWebhook/ in your Teams webhook URL.',
      },
      {
        key: 'webhook_id',
        label: 'Webhook ID',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'wwwwwwww',
        helpText: 'The final path segment in your Teams webhook URL.',
      },
    ],
  },
  {
    service: 'workflows',
    label: 'Microsoft Teams (Workflows)',
    description: 'Send notifications via Microsoft Teams Power Automate (Workflows) webhooks',
    schemes: ['workflows', 'workflow'],
    category: 'chat',
    iconHint: 'teams',
    fields: [
      {
        key: 'webhook_url',
        label: 'Workflow Webhook URL',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'https://….environment.api.powerplatform.com/powerautomate/…/triggers/manual/paths/invoke?…&sig=…',
        helpText: 'In Teams: open the target channel → More options (⋯) → Workflows → "Post to a channel when a webhook request is received" → copy the generated URL. Paste the full HTTPS URL here (it includes the sig token). This replaces the retired Office 365 "Incoming Webhook" connector.',
        validation: { pattern: '^https://' },
      },
      {
        key: 'format',
        label: 'Payload Format',
        type: 'select',
        required: false,
        sensitive: false,
        defaultValue: 'card',
        helpText: 'How the message body is encoded. "Adaptive Card" (default) suits the standard "Post card in a chat or channel" flow. Use "Message envelope" if your flow reads triggerBody()?[\'attachments\'], or "Simple text" for the basic "Send webhook alerts to a channel" template.',
        options: [
          { label: 'Adaptive Card (default)', value: 'card' },
          { label: 'Message envelope (attachments)', value: 'message' },
          { label: 'Simple text', value: 'text' },
        ],
      },
    ],
  },
  {
    service: 'pushover',
    label: 'Pushover',
    description: 'Send push notifications via Pushover to iOS, Android, and desktop',
    schemes: ['pover'],
    category: 'push',
    iconHint: 'pushover',
    fields: [
      {
        key: 'user_key',
        label: 'User Key',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'uQiRzpo4DXghDmr9QzzfQu27cmVRsG',
        helpText: 'Your Pushover user key — found on the main Pushover dashboard at pushover.net after signing in.',
        validation: { minLength: 30, maxLength: 30 },
      },
      {
        key: 'api_token',
        label: 'API Token',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'azGDORePK8gMaC0QOYAMyEEuzJnyUi',
        helpText: 'Your application API token — create an application at pushover.net/apps/build and copy its token.',
        validation: { minLength: 30, maxLength: 30 },
      },
      {
        key: 'device',
        label: 'Device (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'iphone',
        helpText: 'Target a specific device by name. Leave blank to send to all devices.',
      },
    ],
  },
  {
    service: 'pushbullet',
    label: 'Pushbullet',
    description: 'Send push notifications via Pushbullet',
    schemes: ['pbul'],
    category: 'push',
    iconHint: 'pushbullet',
    fields: [
      {
        key: 'access_token',
        label: 'Access Token',
        type: 'text',
        required: true,
        sensitive: true,
        placeholder: 'o.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        helpText: 'Your Pushbullet access token — found at pushbullet.com → Settings → Account → Access Tokens → Create Access Token.',
      },
      {
        key: 'device_id',
        label: 'Device ID (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'ujpah72o0sjAoRtnM0jc',
        helpText: 'Target a specific device by its iden value. Leave blank to push to all devices. Find device iden via the Pushbullet API at api.pushbullet.com/v2/devices.',
      },
      {
        key: 'channel',
        label: 'Channel Tag (optional)',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: 'mychannel',
        helpText: 'Push to a Pushbullet channel instead of a device. Enter the channel tag (without #).',
      },
    ],
  },
  {
    service: 'webhook',
    label: 'Custom Webhook',
    description: 'POST to any HTTP/HTTPS endpoint with JSON or form-encoded body',
    schemes: ['json', 'jsons', 'form', 'forms'],
    category: 'webhook',
    iconHint: 'webhook',
    fields: [
      {
        key: 'host',
        label: 'Host',
        type: 'text',
        required: true,
        sensitive: false,
        placeholder: 'example.com',
        helpText: 'The hostname of your webhook endpoint (without http:// or https://).',
      },
      {
        key: 'path',
        label: 'Path',
        type: 'text',
        required: false,
        sensitive: false,
        placeholder: '/webhook/notify',
        defaultValue: '/',
        helpText: 'The URL path of your webhook endpoint.',
      },
      {
        key: 'secure',
        label: 'Use HTTPS',
        type: 'boolean',
        required: false,
        sensitive: false,
        defaultValue: true,
        helpText: 'Use HTTPS (recommended). Disable only for local/development servers.',
      },
      {
        key: 'format',
        label: 'Body Format',
        type: 'select',
        required: false,
        sensitive: false,
        defaultValue: 'json',
        helpText: 'How to encode the request body.',
        options: [
          { label: 'JSON (application/json)', value: 'json' },
          { label: 'Form (application/x-www-form-urlencoded)', value: 'form' },
        ],
      },
      {
        key: 'method',
        label: 'HTTP Method',
        type: 'select',
        required: false,
        sensitive: false,
        defaultValue: 'POST',
        options: [
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'PATCH', value: 'PATCH' },
        ],
        helpText: 'HTTP method to use. POST is the standard for webhooks.',
      },
    ],
  },
];
