name = "notifly-website"
compatibility_date = "2025-03-27"

[assets]
directory = "./dist"

[[routes]]
pattern = "notifly.sh"
custom_domain = true

[[routes]]
pattern = "www.notifly.sh"
custom_domain = true
