name: First Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ambersecurityinc-runner
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm run build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
